### ISSUE TITLE
Where is the advantage of the method in audio conversion?

### ISSUE THREAD

**Issue by dj181356288** [hujinsen/StarGAN-Voice-Conversion#1]
Where is the advantage of the method in audio conversion?

**Comment by hujinsen** [comment]
hi，
In general StarGAN-VC has four characteristics:
(1) requires neither parallel utterances, transcriptions, nor time alignment procedures for speech generator training.
(2) simultaneously learns many-to-many mappings across different attribute domains using a single generator network
 (3) is able to generate signals of converted speech quickly enough to allow for real-time implementations  
(4) requires only several minutes of training examples to generate reasonably realistic-sounding speech.
More details in the paper.
