### ISSUE TITLE
How to use the non-parallel dataset to train this model?

### ISSUE THREAD

**Issue by star5o** [hujinsen/StarGAN-Voice-Conversion#10]
How to use the non-parallel dataset to train this model?
I want use different dataset which have many audios with name but non-parallel, can i just put the dataset into train_dir and test_dir?
Thanks!

**Comment by star5o** [comment]
@hujinsen I look forward to your reply. Thanks

**Comment by Lukelluke** [comment]
After my test, it's ok to train with non_parallel_data in train_dir, it's just the VCC2016 data that provide the parallel data.

**Comment by crashcar** [comment]
> After my test, it's ok to train with non_parallel_data in train_dir, it's just the VCC2016 data that provide the parallel data.

is the result good？
