### ISSUE TITLE
Issues in training the model

### ISSUE THREAD

**Issue by ghost** [hujinsen/StarGAN-Voice-Conversion#11]
python train.py
Loading Data...
found stat file: ./etc/children-stats.npz
found stat file: ./etc/adult-stats.npz
Loading Data Done.
d1: [None, 36, 512, 32]
d2: [None, 18, 256, 64]
d3: [None, 9, 128, 128]
d4: [None, 9, 128, 64]
[None, 1, 128, 4]
u1.shape :[None, 9, 128, 64]
c1 shape: (?, 9, 128, 4)
u1_concat.shape :[None, 9, 128, 68]
u2.shape :[None, 9, 128, 128]
u3.shape :[None, 18, 256, 64]
u4.shape :[None, 36, 512, 32]
u4_concat.shape :[None, 36, 512, 36]
u5.shape :[None, 36, 512, 1]
d1: [None, 36, 512, 32]
d2: [None, 18, 256, 64]
d3: [None, 9, 128, 128]
d4: [None, 9, 128, 64]
[None, 1, 128, 4]
u1.shape :[None, 9, 128, 64]
c1 shape: (?, 9, 128, 4)
u1_concat.shape :[None, 9, 128, 68]
u2.shape :[None, 9, 128, 128]
u3.shape :[None, 18, 256, 64]
u4.shape :[None, 36, 512, 32]
u4_concat.shape :[None, 36, 512, 36]
u5.shape :[None, 36, 512, 1]
d1: [None, 36, 512, 32]
d2: [None, 18, 256, 64]
d3: [None, 9, 128, 128]
d4: [None, 9, 128, 64]
[None, 1, 128, 4]
u1.shape :[None, 9, 128, 64]
c1 shape: (?, 9, 128, 4)
u1_concat.shape :[None, 9, 128, 68]
u2.shape :[None, 9, 128, 128]
u3.shape :[None, 18, 256, 64]
u4.shape :[None, 36, 512, 32]
u4_concat.shape :[None, 36, 512, 36]
u5.shape :[None, 36, 512, 1]
domain_classifier_d1: (?, 8, 512, 8)
domain_classifier_d1_p: (?, 4, 256, 8)
domain_classifier_d12: (?, 4, 256, 16)
domain_classifier_d2_p: (?, 2, 128, 16)
domain_classifier_d3: (?, 2, 128, 32)
domain_classifier_d3_p: (?, 1, 64, 32)
domain_classifier_d4: (?, 1, 64, 16)
domain_classifier_d4_p: (?, 1, 32, 16)
domain_classifier_d5: (?, 1, 32, 4)
domain_classifier_d5_p: (?, 1, 16, 4)
classifier_output: (?, 1, 1, 4)
domain_classifier_d1: (?, 8, 512, 8)
domain_classifier_d1_p: (?, 4, 256, 8)
domain_classifier_d12: (?, 4, 256, 16)
domain_classifier_d2_p: (?, 2, 128, 16)
domain_classifier_d3: (?, 2, 128, 32)
domain_classifier_d3_p: (?, 1, 64, 32)
domain_classifier_d4: (?, 1, 64, 16)
domain_classifier_d4_p: (?, 1, 32, 16)
domain_classifier_d5: (?, 1, 32, 4)
domain_classifier_d5_p: (?, 1, 16, 4)
classifier_output: (?, 1, 1, 4)
d1: [None, 36, 512, 32]
d2: [None, 18, 256, 64]
d3: [None, 9, 128, 128]
d4: [None, 9, 128, 64]
[None, 1, 128, 4]
u1.shape :[None, 9, 128, 64]
c1 shape: (?, 9, 128, 4)
u1_concat.shape :[None, 9, 128, 68]
u2.shape :[None, 9, 128, 128]
u3.shape :[None, 18, 256, 64]
u4.shape :[None, 36, 512, 32]
u4_concat.shape :[None, 36, 512, 36]
u5.shape :[None, 36, 512, 1]
2019-03-12 12:55:15.378518: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "train.py", line 282, in <module>
    train(processed_dir, test_wav_dir)
  File "train.py", line 158, in train
    lambda_classifier=lambda_classifier
  File "/home/StarGan/model.py", line 148, in train
    self.generator_learning_rate: generator_learning_rate})
  File "/homeStarGan/myvenv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/StarGan/myvenv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1111, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (8, 2) for Tensor 'source_label:0', which has shape '(?, 4)'

Python-v:3.6
Tensorflow:1.8

Help Appericiated

**Comment by praveenece443** [comment]
Hello sir,
jst now i was running the python3 train.py file .  i had faced this issue...plz tell me how can u resolve this issue...

 from ._conv import register_converters as _register_converters
Loading Data...
found stat file: ./etc/SM2-stats.npz
found stat file: ./etc/TF1-stats.npz
found stat file: ./etc/TM2-stats.npz
found stat file: ./etc/TM3-stats.npz
found stat file: ./etc/SM1-stats.npz
found stat file: ./etc/SF1-stats.npz
found stat file: ./etc/SF3-stats.npz
found stat file: ./etc/TM1-stats.npz
Traceback (most recent call last):
  File "/home/intel/Desktop/StarGAN-Voice-Conversion-master/utility.py", line 57, in normalizer_dict
    stat_filepath = [fn for fn in glob.glob(p) if one_speaker in fn][0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 282, in <module>
    train(processed_dir, test_wav_dir)
  File "train.py", line 48, in train
    normlizer = Normalizer()
  File "/home/intel/Desktop/StarGAN-Voice-Conversion-master/utility.py", line 29, in __init__
    self.norm_dict = self.normalizer_dict()
  File "/home/intel/Desktop/StarGAN-Voice-Conversion-master/utility.py", line 59, in normalizer_dict
    raise Exception('====no match files!====')
Exception: ====no match files!====

**Comment by hujinsen** [comment]
Bugs fixed ,please checkout new code.

**Comment by Husnain08** [comment]
I am using the new code and getting the same issue. Please help.

**Comment by Husnain08** [comment]
This error is not solved with the new code. Please help

**Comment by hujinsen** [comment]
Hello, I can't reproduce your problem. It is recommended to check the [speaker's file path](https://github.com/hujinsen/StarGAN-Voice-Conversion/blob/c84e1d03b0f991d7092ac288cda86f4865089bdd/utility.py#L26) to ensure that this is correct.

**Comment by Husnain08** [comment]
Let me try this

**Comment by Husnain08** [comment]
Dear @hujinsen,
Can you please give 10 - 15 minutes of your time and have a skype call with me where I will share the screen with you and maybe then we can find out the answer. I know it's a lot to ask but I have been working on this code for 3 weeks now and I have gotten nowhere. Please let me know if you can spare some time. Please leave your email or contact me at Muhammadhusnain08@gmail.com 
Thanks

**Comment by bhaskarkumar1** [comment]
> Hello, I can't reproduce your problem. It is recommended to check the [speaker's file path](https://github.com/hujinsen/StarGAN-Voice-Conversion/blob/c84e1d03b0f991d7092ac288cda86f4865089bdd/utility.py#L26) to ensure that this is correct.

hey, I am facing the same issue , Need help @hujinsen 
How did you solved @Husnain08
Please reply to this or contact me at  thisisofficialbk@gmail.com
