### ISSUE TITLE
Audio files generated after conversion cannot be opened

### ISSUE THREAD

**Issue by harirawat** [hujinsen/StarGAN-Voice-Conversion#14]

**Comment by harirawat** [comment]
I used Google Colab to train the model. On opening the converted .wav files generated from the following command, the files are not getting opened with the error message - there is a problem opening this audio file.
```python convert.py --model_dir ./out/1_2019-06-26-14-09/model  --source_speaker SF1 --target_speaker SF2```

**Comment by hujinsen** [comment]
I didn't test the code in colab, you can refer to the closed issues for similar problems.

**Comment by xudongxiang** [comment]
use soundfile other than librosa to save file and you can sovle this problem
