### ISSUE TITLE
what should i do if i want to use more speakers data

### ISSUE THREAD

**Issue by keevinzha** [hujinsen/StarGAN-Voice-Conversion#15]
I have changed SPEAKERS_NUM, but got shape problem

**Comment by hujinsen** [comment]
Modify the code below so that the classifier outputs the same number of categories as your speaker

`https://github.com/hujinsen/StarGAN-Voice-Conversion/blob/c84e1d03b0f991d7092ac288cda86f4865089bdd/module.py#L276`
