### ISSUE TITLE
KeyError: 'coded_sps_mean'

### ISSUE THREAD

**Issue by raanubis** [hujinsen/StarGAN-Voice-Conversion#18]
OS: Windows
I'm only changed some code that the folders and files will be work on windows, the rest of the code is untouched.

If i start train.py 
python train.py --processed_dir .\data\processed --test_wav_dir .\data\fourspeakers_test

I get the error: 

`Traceback (most recent call last):
  File "train.py", line 266, in <module>
    train(processed_dir, test_wav_dir)
  File "train.py", line 115, in train
    one_file = normlizer.forward_process(one_file, speaker_name)
  File "C:\work\StarGAN-Voice-Conversion\utility.py", line 33, in forward_process
    mean = self.norm_dict[speakername]['coded_sps_mean']
KeyError: 'coded_sps_mean'`

in the array of 'speakername' are the dict keys:
dict_keys(['f0', 'ap', 'sp', 'coded_sp'])

Any idea how i could fix it?

**Comment by hujinsen** [comment]
The code only tested on ubuntu 16.04

**Comment by merveyyildiz** [comment]
hi raanubis, i have the same problem. Did you solve the problem?
