### ISSUE TITLE
ValueError: Object arrays cannot be loaded when allow_pickle=False

### ISSUE THREAD

**Issue by salisbury-espinosa** [hujinsen/StarGAN-Voice-Conversion#19]
> [485:486]svaing file: ./data/processed/TM1-100131_0.npy
> [485:486]svaing file: ./data/processed/TM1-100131_512.npy
> save file: ./data/processed/TM1-100132
> audio mcep shape (36, 512)
> [486:486]svaing file: ./data/processed/TM1-100132_0.npy
> Traceback (most recent call last):
>   File "preprocess.py", line 200, in <module>
>     generator.generate_stats()
>   File "/home/user/sources/StarGAN-Voice-Conversion/utility.py", line 158, in generate_stats
>     d = t.f.arr_0.item()
>   File "/home/user/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 94, in __getattribute__
>     return object.__getattribute__(self, '_obj')[key]
>   File "/home/user/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 262, in __getitem__
>     pickle_kwargs=self.pickle_kwargs)
>   File "/home/user/.local/lib/python3.6/site-packages/numpy/lib/format.py", line 722, in read_array
>     raise ValueError("Object arrays cannot be loaded when "
> ValueError: Object arrays cannot be loaded when allow_pickle=False

**Comment by reitowo** [comment]
conda install numpy=1.16.2

**Comment by yeshanew** [comment]
conda install numpy=1.16.1  is working

**Comment by bhaskarkumar1** [comment]
Ya, conda install numpy=1.16.2 this working. thank you  cnSchwarzer

**Comment by bhaskarkumar1** [comment]
hey admin @hujinsen  or @salisbury-espinosa you can close these issues. As this issue got solved.
