### ISSUE TITLE
How to solve KeyError: 'coded_sps_mean' ?

### ISSUE THREAD

**Issue by navinthenapster** [hujinsen/StarGAN-Voice-Conversion#5]
i looked into the code in utility.py . This mean calculation happens in func generate_stats .. But where generate_stats is called? Please help me with it

**Comment by hujinsen** [comment]
hi, the code is [called](https://github.com/hujinsen/StarGAN-Voice-Conversion/blob/00abc81acddda348188574355f9d4e5b0284b32c/preprocess.py#L200) in preprocess.py
