### ISSUE TITLE
why train the classifier in parallel with the generator and the discriminator?

### ISSUE THREAD

**Issue by kstoneriv3** [hujinsen/StarGAN-Voice-Conversion#6]
I want to know why you do not train the classifier in advance.
To me, it seems that the classifier can be trained separately from the other sub-models.

**Comment by hujinsen** [comment]
Maybe you're right. In some previous works about voice conversion(VAE-WGAN), there's no classifier the     
converted results are also good. You'd better try out different settings of the experiment to find out the answer.
