### ISSUE TITLE
Exception: ====no match files!====

### ISSUE THREAD

**Issue by leokwu** [hujinsen/StarGAN-Voice-Conversion#7]
platform: ubuntu 18.04

process:
python3.6 train.py --processed_dir ./data/processed --test_wav_dir ./data/fourspeakers_test      

issue log:
t_wav_dir ./data/fourspeakers_test      
Loading Data...
found stat file: ./etc/TM1-stats.npz
Traceback (most recent call last):
  File "StarGAN-Voice-Conversion/utility.py", line 57, in normalizer_dict
    stat_filepath = [fn for fn in glob.glob(p) if one_speaker in fn][0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 282, in <module>
    train(processed_dir, test_wav_dir)
  File "train.py", line 48, in train
    normlizer = Normalizer()
  File "StarGAN-Voice-Conversion/utility.py", line 29, in __init__
    self.norm_dict = self.normalizer_dict()
  File "StarGAN-Voice-Conversion/utility.py", line 59, in normalizer_dict
    raise Exception('====no match files!====')
Exception: ====no match files!====

Download dataset-->Preprocess dataset -->Train
processed dataset already pass, but train above error occurred, Can you provide guidance?

tks.

**Comment by hujinsen** [comment]
please check if the ./etc contains speaker statistics for all speakers.

**Comment by leokwu** [comment]
Y，I am sure contains speaker statistics for all speakers.

ls -al ./etc

-rw-r--r-- 1 1599 12 22 12:44 SF1-stats.npz
-rw-r--r-- 1 1585 12 22 12:46 SF2-stats.npz
-rw-r--r-- 1 1598 12 22 12:44 SF3-stats.npz
-rw-r--r-- 1 1584 12 22 12:44 SM1-stats.npz
-rw-r--r-- 1 1586 12 22 12:43 SM2-stats.npz
-rw-r--r-- 1 1580 12 22 12:45 TF1-stats.npz
-rw-r--r-- 1 1590 12 22 12:45 TF2-stats.npz
-rw-r--r-- 1  1595 12 22 12:42 TM1-stats.npz
-rw-r--r-- 1 1593 12 22 12:42 TM2-stats.npz
-rw-r--r-- 1 1585 12 22 12:43 TM3-stats.npz


Any errors about the above?

**Comment by hujinsen** [comment]
The reason may be index empty list. so, I personally suggest you to debug [here](https://github.com/hujinsen/StarGAN-Voice-Conversion/blob/109563476ac125647232495e0b126b7c41101807/utility.py#L49).
first check self.all_speakers is: SF1....TM3 and glob.glob() get the desired output.

I'm sorry , the code is a little messy and I'll update it in a few days.

**Comment by leokwu** [comment]
tks for Y tips, i will try Y proposal & follow Y future commit.

tks a lot.

**Comment by leokwu** [comment]
remove data/fourspeakers/README  can reslove this problem.

**Comment by Husnain08** [comment]
I get the same problem. I cannot solve it. Can you help me ?
