### ISSUE TITLE
About the final result

### ISSUE THREAD

**Issue by noooahyao** [hujinsen/StarGAN-Voice-Conversion#9]
I am curious about I can't open the final result, except using sox in linux and encode it into 32bit or 16 bit, BTW have you had a good result, I have tried some non-parallel data, and the result is bad. Though i can specify the voice after conversion, but the voice is not clear, do you have any advise on improving the voice qulity

**Comment by mahmoudalismail** [comment]
Have you tried examining the results at different iterations in the training? At some iterations, you can definitely find a good balance between voice conversion and the intelligibility of speech.

**Comment by hujinsen** [comment]
The code has been updated. Bugs have been modified and the results generated are better than before. 
Please use the new code.

**Comment by partha2409** [comment]
I also face a similar problem. The intelligibilty of converted speech is poor, Did you get any insights @yaoyidian ? Although i trained on a custom dataset, even on VCC dataset i feel the intelligibility can still be better. What are the hyper parameters do you suggest tuning to improve this?
